services:
  database:
    image: 'postgres:16-alpine'
    ports:
      - '15432:5432'
    environment:
      - 'POSTGRES_USER=lotteryadmin'
      - 'POSTGRES_DB=lottery'
      - 'POSTGRES_PASSWORD=secret'
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
